### ISSUE TITLE
release date

### ISSUE THREAD

**Issue by minouei-kl** [fzi-forschungszentrum-informatik/NNAD#1]
Hi,
is there any plan to release the codes?

**Comment by olesalscheider** [comment]
This repository already contains code for different projects. There are different branches corresponding to different publications. Which one are you interested in? The README in the master branch should point you to the right branch name

I know that this use of branches is somewhat uncommon - it is mostly a result of our internal organization. I hope that it does not create too much confusion.

**Comment by minouei-kl** [comment]
glad to hear that, and yes it is uncommon I didn't notice it at first :+1:
