### ISSUE TITLE
What versions are you using?

### ISSUE THREAD

**Issue by Freephi** [fzi-forschungszentrum-informatik/NNAD#6]
Hi, thank you for your great paper and for making your code publicly available. 
I wanted to try your code, but did not get it to compile correctly. 
Therefore I wanted to ask you what versions of the modules you have installed. 
In your Readme you wrote Tensorflow 2, but your FindTensorflow.cmake has this section: 
`find_library(TENSORFLOW_LIBRARY libtensorflow_framework.so.1 HINTS ${TF_LIB_DIR} NO_DEFAULT_PATH)`
which let me assume that you compiled with tensorflow 1.x as tensorflow 2.x only produces libtensorflow_framework.so.2.
I managed to get the code compiled with tensorflow 1.15, but your code seems only to work with tensorflow >= 2.x. 
When I try to compile the code with TF 2.x I get the following error while running the pretrain.py:
`tensorflow.python.framework.errors_impl.NotFoundError: /home/NNAD/data/build/libdataset_op.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb`

I already searched the internet, but none of the proposed solutions worked. 
Do you know how this could be solved, or could you please share the versions you've used. 

I tried python 3.6 and 3.8 and with both the tensorflow versions 2.4 and 2.6 

Any help is highly appreciated!

**Comment by olesalscheider** [comment]
You actually need TF 2 to compile my code. At least my build of TF2 produced libtensorflow_framework.so.1 back then, but it might have changed.

Version 2.6 should work. The error that you are getting occurs if the Tensorflow binary uses a different C++ ABI than the compiled module. Which GCC version are you using?

**Comment by Freephi** [comment]
Thank you for your fast response! I've managed to get it running with Tensorflow 2.2.
